
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      first:  #数据源1
        url: jdbc:mysql://b152273m45.zicp.fun:40582/xingang?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
      second:  #数据源2
        url: jdbc:mysql://localhost:3306/xingang_dataset?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          678-sql: true
        wall:
          config:
            multi-statement-allow: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
server:
  port: 8086
  mybatis:
    mapper-locations=classpath:mapper/*Mapper:
      xml: classpath:mapper/*Mapper.xml